# Generated by Django 5.2.8 on 2025-12-15 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_first_name_employee_first_name1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='first_name1',
            new_name='first_name',
        ),
    ]
