# Generated by Django 5.2.8 on 2025-12-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_first_name1_employee_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
