# Generated by Django 5.2.8 on 2025-12-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
