# Generated by Django 6.0.2 on 2026-02-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0007_employee_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
