# Generated by Django 6.0.2 on 2026-02-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userextend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logs',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='logs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
