# Generated by Django 5.2.8 on 2025-12-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('department', models.CharField(choices=[('hr', 'Human Resources'), ('it', 'Information Technology'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('finance', 'Finance')], max_length=20)),
                ('hire_date', models.DateField()),
            ],
        ),
    ]
