# Generated by Django 6.0.2 on 2026-02-17 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='manager',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
