# Generated by Django 6.0.2 on 2026-02-17 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_manager_date_joined_manager_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['department', 'last_name', 'first_name'], 'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
        migrations.RemoveField(
            model_name='manager',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='position',
        ),
        migrations.AddField(
            model_name='manager',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='department',
            field=models.CharField(choices=[('hr', 'Human Resources'), ('it', 'Information Technology'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('finance', 'Finance')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(db_index=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='manager',
            name='last_name',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['department', 'active'], name='manager_man_departm_8870f7_idx'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['last_name', 'first_name'], name='manager_man_last_na_49795e_idx'),
        ),
    ]
